// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package shakespert

import (
	"database/sql"
)

type Chapter struct {
	Workid      sql.NullString
	Chapterid   int64
	Section     sql.NullInt64
	Chapter     sql.NullInt64
	Description sql.NullString
}

type Character struct {
	Charid      string
	Charname    sql.NullString
	Abbrev      sql.NullString
	Works       sql.NullString
	Description sql.NullString
	Speechcount sql.NullInt64
}

type Genre struct {
	Genretype string
	Genrename sql.NullString
}

type Paragraph struct {
	Workid        sql.NullString
	Paragraphid   int64
	Paragraphnum  sql.NullInt64
	Charid        sql.NullString
	Plaintext     sql.NullString
	Phonetictext  sql.NullString
	Stemtext      sql.NullString
	Paragraphtype interface{}
	Section       sql.NullInt64
	Chapter       sql.NullInt64
	Charcount     sql.NullInt64
	Wordcount     sql.NullInt64
}

type Work struct {
	Workid          string
	Title           sql.NullString
	Longtitle       sql.NullString
	Shorttitle      sql.NullString
	Date            sql.NullInt64
	Genretype       sql.NullString
	Notes           []byte
	Source          sql.NullString
	Totalwords      sql.NullInt64
	Totalparagraphs sql.NullInt64
}
